# 1. write a numpy program to convert list into numpy one dimensional array

In [1]:
## Dhruv Thanki 
## 216270307058
import numpy as np

# creating list of numeric values 
a = [1,2,3,4,5,6,7,8,9,10]

# printing list 
print(" PYTHON LIST : ",a)

# converting list a into nupmy numeric array 
converted_list_into_array = np.array(a)
print()

# printing new numpy array
print(" CONVERTED NUMPY ARRAY : ",converted_list_into_array)
print()

#cheking dimension of converted list 
#ndim is used to check the dimension of numpy array
print(" CHECKING DIMENSION OF NUMPY ARRAY : ",converted_list_into_array.ndim)

 PYTHON LIST :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

 CONVERTED NUMPY ARRAY :  [ 1  2  3  4  5  6  7  8  9 10]

 CHECKING DIMENSION OF NUMPY ARRAY :  1


# 2. write a Numpy program to create a 3x3 matrix with values ranging from 2 to 10

In [2]:
import numpy as np 

# arange() function is used to create array within given range 
array = np.arange(2,11)

#printing crated array
print(" ARRAY : ",array)
print()

# now reshapeing the created array into 3 X 3 matrix 
matrix_array = array.reshape(3,3)

# now printing the matrix_array 
print(" 3 X 3 MATRIX : ")
print()
print(matrix_array)

 ARRAY :  [ 2  3  4  5  6  7  8  9 10]

 3 X 3 MATRIX : 

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 3. write a program to append values at the end of the array

In [3]:
import numpy as np

# creating array with the help of np.array 
array = np.array([1,2,3,4,5])

#appending values in array
array2 = np.append(array, [6,7])
print()

# printing both array 
print(" ARRAY BEFORE APPENDING THE VALUES : ",array)
print()
print(" ARRAY AFTER APPENDING THE VALUES  : ",array2)


 ARRAY BEFORE APPENDING THE VALUES :  [1 2 3 4 5]

 ARRAY AFTER APPENDING THE VALUES  :  [1 2 3 4 5 6 7]


# 4. write a program to create another shape from an array without changing its data(32 to 23)

In [4]:
import numpy as np

# creating 3 X 2 array 
array = np.array([ [1,2] , [1,2], [1,2] ])

# now changing the shape of 3 X 2 array
array2 = array.reshape(2,3)

# printing both arrays
print()
print(" 3 X 2 ARRAY : ")
print(array)

print()
print(" 2 X 3 ARRAY : ")
print(array2)


 3 X 2 ARRAY : 
[[1 2]
 [1 2]
 [1 2]]

 2 X 3 ARRAY : 
[[1 2 1]
 [2 1 2]]
